### ISSUE TITLE
Changing the project's name to avoid confusion 

### ISSUE THREAD

**Issue by theAkito** [Akito13/plumbly#1]
On my private repository I renamed this project to "plumbly" and the main dependency Jumble to "jumbly" because I want to avoid confusion when people tell someone to download Plumble or when they are talking about it. I don't something like "I just downloaded Plumble on my phone. - No, I mean the newer one.". That's why I think it would be a good idea to change the name slightly, as I already did. What do you think?

**Comment by iammeat** [comment]
Agreed.  Bumble.  With a Bee icon. :-D

**Comment by iammeat** [comment]
Can we also get write access to the wiki?  I think it's important that we have documentation.

**Comment by iammeat** [comment]
Bumble for the app, Rumble for the library.

**Comment by theAkito** [comment]
@iammeat I sent you an invite link. 😃 



> 
> 
> Bumble for the app, Rumble for the library.

The reason I chose the names mentioned i.e. "plumbly" and "jumbly" is because I want to avoid colleration with other project. E.g. "Rumble" is a common word anyone could use and probably is used many times already. On the other hand, last time I checked "plumbly" and "jumbly" were unique, so I chose these.

I think I am going to change the name(s) for now, to avoid confusion. If a specific reason for choosing a different name comes up, the discussion will be opened up, again.

**Comment by iammeat** [comment]
Invite accepted.  Thank you.

Those names are unique, sure, but they're pretty hard to say!  Let's tackle that again later when we have a release worthy of a new name.

**Comment by iammeat** [comment]
@Akito13 what's the best way to contact you, rather than chatting in issues?  Discord?  Instagram?  I found a user with the same name on Insta and added them (from my account joegoeswild).  Let me know if this is you.

**Comment by iammeat** [comment]
The reason I ask is because the gradle fixes I am performing need to be done on *both* the app project and the jumbly submodule for it to work properly, and I've made changes to the NDK configuration so the path is detected properly automatically.  I've almost got it to build, except for the spongycastle errors because nested libraries don't work the way they used to.

**Comment by Akito13** [comment]
@iammeat No worries. Send me your e-mail address and I will text you there.

**Comment by iammeat** [comment]
@Akito13 use geekoid@gmail.com
